version: '3.8'
services:
  nginx1:
    build:
      dockerfile: nginx-df
    image: huehuehue
    container_name: con1
    ports:
      - "6666:80"
    volumes:
      - abc:/data
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
volumes:
  abc:  
